name: Deploy

on: 
 workflow_dispatch:
    inputs:
      region:
        required: true
        type: choice
        options:
        - us
        - staging
        - eu
        - au
     
      version_number:
        required: true
        type: string
      
      type:
        required: true
        type: choice 
        options:
        - frontend
        - backend
        - optifrontend
        
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:   
    - uses: actions/checkout@v1
    - name: edit something
      run: echo "something"
     
    - name: Upload Documentation to Wiki
      uses: SwiftDocOrg/github-wiki-publish-action@v1
      with:
          path: "data.json"
      env:
          GH_PERSONAL_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN  }}
