name: Deploy

on: 
 workflow_dispatch:
    inputs:
      region:
        required: true
        type: choice
        options:
        - us
        - staging
        - eu
        - au
     
      version_number:
        required: true
        type: string
      
      type:
        required: true
        type: choice 
        options:
        - frontend
        - backend
        - optifrontend
        
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:   
    - name: Check out repo
      uses: actions/checkout@v2
    - name: Check out wiki
      uses: actions/checkout@v2
      with:
          repository: 'Oksana-Kaliniouk/recipes.wiki'
          ref: 'master'
          path: 'recipes.wiki'

    - name: Commit changes
      shell: bash
      run : |
        cd  $GITHUB_WORKSPACE/recipes.wiki
        echo -e "$(date +'%Y-%m-%d %H:%M:%S %Z') $GITHUB_ACTOR deployed to ${{ inputs.region }}-${{ inputs.type }}  version ${{ inputs.version_number }}\n\n$(cat version.md)" > version.md   
        git config --local user.email "actions@github.com"
        git config --local user.name "Github Action"
        git add version.md
        git commit -a -m "updating version to ${{ inputs.version_number }}"
        git push
        
    - name: Push changes
      uses: ad-m/github-push-action@master
      with: 
        github_token: ${{secrets.GITHUB_TOKEN}}      
